import type { Prisma } from "@prisma/client";

type ProjectSeed = Omit<Prisma.ProjectCreateInput, "submissions">;

const q = (question: string, keywords: string[]) => ({ question, keywords });

export const projects: ProjectSeed[] = [
  {
    slug: "cli-todo",
    rung: 1,
    title: "CLI to-do app with file storage",
    description:
      "Ek command-line to-do app banao jo tasks ko ek JSON file mein save kare. `add`, `list`, `done`, `delete` commands hone chahiye. Restart karne ke baad bhi tasks wapas aane chahiye.",
    skills: ["Language basics", "Functions", "Files"],
    technologies: ["Python or Node.js"],
    difficulty: 1,
    stageSlug: "foundations",
    requirements: [
      "Commands: add <text>, list, done <id>, delete <id>",
      "Tasks persist in a JSON file between runs",
      "Friendly error when an id does not exist",
      "README explaining how to run it",
    ],
    milestones: [
      { title: "Parse commands", description: "Read the command and arguments from the terminal." },
      { title: "Store tasks", description: "Load and save the task list to tasks.json." },
      { title: "Edge cases", description: "Handle missing file, bad ids and empty input." },
    ],
    hints: [
      "Concept: a program is input → process → output. Here the input is command-line arguments and the storage is a JSON file.",
      "Step: write load_tasks() and save_tasks() first, then one function per command, then a small dispatcher that picks the function from the command name.",
      "Partial code: `const [cmd, ...rest] = process.argv.slice(2)` (Node) or `cmd, *rest = sys.argv[1:]` (Python).",
    ],
    explainQuestions: [
      q("Why did you store tasks in a JSON file instead of a variable?", ["persist", "restart", "file", "memory"]),
      q("What happens if tasks.json does not exist yet, and how did you handle it?", ["exist", "create", "empty", "error"]),
      q("How do you make sure deleting task 3 doesn't delete the wrong task?", ["id", "unique", "check", "index"]),
    ],
    status: "PUBLISHED",
  },
  {
    slug: "portfolio-website",
    rung: 2,
    title: "Responsive portfolio website",
    description: "Apna portfolio banao — semantic HTML, responsive layout (mobile se desktop tak), Tailwind CSS, aur live deploy.",
    skills: ["HTML", "CSS", "Tailwind", "Deployment"],
    technologies: ["HTML", "Tailwind CSS", "Vercel / Netlify"],
    difficulty: 1,
    stageSlug: "frontend",
    requirements: ["Semantic HTML sections: hero, projects, skills, contact", "Works from 360px to desktop", "Accessible: alt text, labels, keyboard focus", "Deployed with a public URL"],
    milestones: [
      { title: "Structure", description: "Semantic HTML skeleton." },
      { title: "Responsive styling", description: "Mobile-first layout with Tailwind." },
      { title: "Deploy", description: "Ship to Vercel or Netlify." },
    ],
    hints: [
      "Concept: mobile-first means you style the small screen first and add breakpoints (md:, lg:) for bigger screens.",
      "Step: build the hero, then a projects grid using `grid grid-cols-1 md:grid-cols-2`.",
      "Partial code: `<section aria-labelledby=\"projects-title\"><h2 id=\"projects-title\">Projects</h2>...`",
    ],
    explainQuestions: [
      q("Why did you use semantic tags like <section> and <nav> instead of only <div>?", ["accessibility", "screen reader", "seo", "meaning"]),
      q("How does your layout change between mobile and desktop?", ["breakpoint", "mobile", "grid", "flex"]),
      q("How did you deploy it and what happens when you push a change?", ["deploy", "build", "push", "vercel|netlify"]),
    ],
    status: "PUBLISHED",
  },
  {
    slug: "weather-search",
    rung: 3,
    title: "Weather or movie search app using a public API",
    description: "Search box se public API call karo, loading / error / empty states dikhao, aur results achhe se render karo.",
    skills: ["Fetching data", "Async", "Error states"],
    technologies: ["JavaScript", "fetch", "Public API"],
    difficulty: 2,
    stageSlug: "javascript",
    requirements: ["Search input with debounce", "Loading, error and empty states", "API key never committed to Git", "Handles network failure gracefully"],
    milestones: [
      { title: "Call the API", description: "fetch + async/await with error handling." },
      { title: "UI states", description: "Loading, error, empty and success." },
      { title: "Polish", description: "Debounce and keyboard support." },
    ],
    hints: [
      "Concept: every network call has 4 states — idle, loading, success, error. Model all of them.",
      "Step: write `async function search(query)` with try/catch, check `res.ok`, then render.",
      "Partial code: `const res = await fetch(url); if (!res.ok) throw new Error(`HTTP ${res.status}`);`",
    ],
    explainQuestions: [
      q("What happens in your app when the API is down?", ["error", "catch", "message", "status"]),
      q("Why did you debounce the search input?", ["debounce", "requests", "typing", "rate"]),
      q("Where is your API key stored and why?", ["env", "secret", "commit", "key"]),
    ],
    status: "PUBLISHED",
  },
  {
    slug: "notes-api",
    rung: 4,
    title: "REST API for a notes app with auth",
    description: "Express (ya FastAPI) mein notes API banao: register/login, JWT ya session auth, aur har user sirf apne notes dekh sake (IDOR nahi!).",
    skills: ["Backend", "Database", "JWT", "Validation"],
    technologies: ["Node.js + Express or FastAPI", "PostgreSQL", "JWT"],
    difficulty: 2,
    stageSlug: "backend",
    requirements: ["Register / login with hashed passwords", "CRUD notes scoped to the logged-in user", "Input validation on every route", "Consistent JSON errors and status codes", "Tests for auth and ownership"],
    milestones: [
      { title: "Schema and CRUD", description: "Users and notes tables, CRUD routes." },
      { title: "Auth", description: "Password hashing and JWT/session." },
      { title: "Authorisation", description: "Every query filtered by owner." },
      { title: "Tests", description: "Prove user A can't read user B's note." },
    ],
    hints: [
      "Concept: authentication = who are you; authorisation = what can you touch. IDOR happens when you skip the second.",
      "Step: add `WHERE user_id = $currentUser` to every notes query, then write a test where user B requests user A's note id.",
      "Partial code: `const note = await db.note.findFirst({ where: { id, userId: req.user.id } }); if (!note) return res.status(404)...`",
    ],
    explainQuestions: [
      q("How do you stop one user from reading another user's notes?", ["owner|user id", "filter", "idor", "authoriz"]),
      q("How are passwords stored and why?", ["hash", "bcrypt|argon2", "salt", "plain"]),
      q("What does your API return for invalid input and why that status code?", ["400", "validation", "error", "status"]),
    ],
    status: "PUBLISHED",
  },
  {
    slug: "job-board",
    rung: 5,
    title: "Full-stack job board with search and pagination",
    description: "Next.js frontend + API + PostgreSQL. Jobs search, filters, pagination, aur caching for popular searches.",
    skills: ["React/Next.js", "SQL", "Indexing", "Caching"],
    technologies: ["Next.js", "PostgreSQL", "Redis"],
    difficulty: 2,
    stageSlug: "backend",
    requirements: ["Search by title/company/location", "Cursor or offset pagination", "Indexes for the search query (show EXPLAIN)", "Cache popular queries with TTL"],
    milestones: [
      { title: "Data model", description: "Jobs, companies, indexes." },
      { title: "Search API", description: "Filters + pagination." },
      { title: "Frontend", description: "Search UI with URL state." },
      { title: "Performance", description: "Indexes and caching." },
    ],
    hints: [
      "Concept: an index is like a book's index — it lets the DB jump to rows instead of scanning all of them.",
      "Step: run EXPLAIN ANALYZE on your search query before and after adding an index on the filtered columns.",
      "Partial code: `CREATE INDEX idx_jobs_location_created ON jobs (location, created_at DESC);`",
    ],
    explainQuestions: [
      q("Which index did you add and how did it change the query plan?", ["index", "explain", "scan", "seq|sequential"]),
      q("How do you invalidate cached search results when a job is added?", ["ttl", "invalidate", "cache", "expire"]),
      q("Offset vs cursor pagination — which did you pick and why?", ["offset", "cursor", "page", "performance"]),
    ],
    status: "PUBLISHED",
  },
  {
    slug: "realtime-chat",
    rung: 6,
    title: "Real-time chat app",
    description: "WebSockets se chat rooms, online presence, aur message history.",
    skills: ["WebSockets", "Rooms", "Scaling basics"],
    technologies: ["Socket.IO or ws", "Redis pub/sub"],
    difficulty: 3,
    stageSlug: "backend",
    requirements: ["Rooms and presence", "Message history persisted", "Reconnect handling", "Explain how to scale to 2+ servers"],
    milestones: [
      { title: "Socket server", description: "Connect, join room, send message." },
      { title: "Persistence", description: "Store and load history." },
      { title: "Scale", description: "Redis adapter / pub-sub across instances." },
    ],
    hints: [
      "Concept: HTTP is request/response; WebSocket keeps one connection open so the server can push.",
      "Step: emit to a room, not to everyone: `io.to(roomId).emit('message', msg)`.",
      "Partial code: `socket.on('join', (roomId) => socket.join(roomId));`",
    ],
    explainQuestions: [
      q("Why WebSockets instead of polling?", ["connection", "push", "latency", "polling"]),
      q("What breaks when you run two server instances and how do you fix it?", ["pub/sub|pubsub", "redis", "instance", "adapter"]),
    ],
    status: "PUBLISHED",
  },
  {
    slug: "multi-tenant-saas",
    rung: 7,
    title: "Multi-tenant SaaS booking app with RBAC",
    description: "Salon ya clinic booking SaaS: har business (tenant) ka data alag, roles (owner/staff/customer), aur reminder emails background jobs se.",
    skills: ["Security", "Tenant isolation", "Background jobs"],
    technologies: ["PostgreSQL", "Queues", "RBAC"],
    difficulty: 3,
    stageSlug: "backend",
    requirements: ["Every query scoped by tenantId", "Roles: owner, staff, customer", "Reminder emails via a queue worker", "Tests proving tenant isolation"],
    milestones: [
      { title: "Tenancy model", description: "tenantId on every table." },
      { title: "RBAC", description: "Role checks in middleware." },
      { title: "Jobs", description: "Queue + worker for reminders." },
    ],
    hints: [
      "Concept: in a shared-database multi-tenant app, forgetting one tenant filter leaks another business's data.",
      "Step: centralise tenant scoping in a repository helper so no route builds queries by hand.",
      "Partial code: `function forTenant(tenantId) { return { where: { tenantId } }; }`",
    ],
    explainQuestions: [
      q("How do you guarantee tenant A never sees tenant B's bookings?", ["tenant", "filter|scope", "query", "test"]),
      q("Why send reminders from a background job instead of the request?", ["queue", "background", "slow|latency", "retry"]),
    ],
    status: "PUBLISHED",
  },
  {
    slug: "dockerised-cicd",
    rung: 8,
    title: "Dockerised app with CI/CD to the cloud",
    description: "Apne notes API ko Docker mein pack karo, GitHub Actions se test + build + deploy, Nginx reverse proxy aur health checks ke saath.",
    skills: ["Docker", "GitHub Actions", "AWS", "Nginx", "Monitoring"],
    technologies: ["Docker", "GitHub Actions", "AWS EC2 or Render", "Nginx"],
    difficulty: 3,
    stageSlug: "devops",
    requirements: ["Multi-stage Dockerfile, non-root user", "CI runs lint, tests, build on every PR", "Deploy on merge to main", "Health check endpoint and basic logs/alerts"],
    milestones: [
      { title: "Dockerfile", description: "Small, secure image." },
      { title: "CI", description: "Lint/test/build pipeline." },
      { title: "CD", description: "Automatic deploy + rollback plan." },
    ],
    hints: [
      "Concept: CI proves every change works; CD ships it automatically once it does.",
      "Step: write the workflow in .github/workflows/ci.yml with jobs for install, test, build.",
      "Partial code: `FROM node:22-alpine AS build` ... `USER node`",
    ],
    explainQuestions: [
      q("Why a multi-stage Docker build?", ["size", "stage", "build", "image"]),
      q("How would you roll back a bad deploy?", ["rollback", "previous", "version|tag", "deploy"]),
    ],
    status: "PUBLISHED",
  },
  {
    slug: "rag-document-qa",
    rung: 9,
    title: "Document Q&A with RAG",
    description: "PDFs upload karo, chunks + embeddings banao, vector DB mein store karo, aur sawaal ka jawab sources ke saath do.",
    skills: ["LLM APIs", "Embeddings", "Vector DB"],
    technologies: ["Embeddings API", "pgvector or a vector DB"],
    difficulty: 3,
    stageSlug: "applied-ai",
    requirements: ["Chunking with overlap", "Top-k retrieval with citations", "Refuse when the answer isn't in the documents", "Basic evaluation set"],
    milestones: [
      { title: "Ingest", description: "Chunk and embed documents." },
      { title: "Retrieve + answer", description: "Top-k context into the prompt." },
      { title: "Evaluate", description: "10-question eval with expected answers." },
    ],
    hints: [
      "Concept: RAG = search first, then let the model answer only from what you found.",
      "Step: store (chunk_text, embedding, doc_id) and query by cosine similarity.",
      "Partial code: `SELECT chunk FROM chunks ORDER BY embedding <=> $1 LIMIT 5;`",
    ],
    explainQuestions: [
      q("How did you choose chunk size and overlap?", ["chunk", "overlap", "context", "size"]),
      q("How do you reduce hallucinations?", ["source|citation", "context", "refuse", "retriev"]),
    ],
    status: "PUBLISHED",
  },
  {
    slug: "capstone",
    rung: 10,
    title: "Capstone: design and build a system of your choice",
    description: "Ek real problem choose karo, design doc likho (requirements, scale estimate, API, data model, trade-offs), aur end-to-end build karke deploy karo.",
    skills: ["System design", "End-to-end ownership"],
    technologies: ["Your choice"],
    difficulty: 3,
    stageSlug: "system-design",
    requirements: ["Design doc with requirements, estimates, API, data model, trade-offs", "Working deployed system", "Tests and monitoring", "A 2-minute project pitch"],
    milestones: [
      { title: "Design doc", description: "Reviewed before building." },
      { title: "Build", description: "Core flows end to end." },
      { title: "Ship", description: "Deploy, monitor, write the story." },
    ],
    hints: [
      "Concept: a design doc is for decisions — what you chose and what you gave up.",
      "Step: start from requirements and a back-of-envelope estimate, then pick storage and APIs.",
      "Partial code: N/A — write the doc headings first: Problem, Requirements, Estimates, API, Data, Architecture, Trade-offs.",
    ],
    explainQuestions: [
      q("What was the hardest trade-off in your design?", ["trade-off|tradeoff", "chose", "because", "alternative"]),
      q("Where is the bottleneck at 10x traffic and how would you fix it?", ["bottleneck", "scale", "cache|replica|queue", "traffic"]),
      q("How do you know your system is healthy in production?", ["monitor", "metric|log", "alert", "health"]),
    ],
    status: "PUBLISHED",
  },
];

export const extraInterviewQuestions: Prisma.InterviewQuestionCreateManyInput[] = [
  {
    category: "HR",
    question: "Tell me about yourself.",
    short: "I'm a final-year computer science student focused on backend development. I've built and deployed a notes API with JWT auth and a full-stack job board, and I enjoy debugging and designing data models. I'm looking for a backend role where I can ship reliable APIs.",
    deep: "Use **present → past → future**: what you do now, 1–2 proof points (projects with numbers), and why this role. Keep it under 90 seconds and end with a hook the interviewer can ask about.",
    followUps: ["Which project are you most proud of?", "Why backend and not frontend?"],
    commonMistake: "Reading your resume line by line or talking about hobbies for a minute.",
    keywords: ["project", "built", "role", "experience|skills"],
    difficulty: 1,
    roles: ["BACKEND", "FRONTEND", "FULLSTACK", "DEVOPS", "SDE"],
  },
  {
    category: "HR",
    question: "What is your biggest weakness?",
    short: "I used to over-polish code before getting feedback. Now I share a working draft early, ask for review, and time-box polishing — it has made me faster and my PRs smaller.",
    deep: "Pick a **real, non-fatal** weakness, show the **action** you took, and the **result**. Avoid fake weaknesses like 'I work too hard'.",
    followUps: ["Give me an example from a project."],
    commonMistake: "Choosing a weakness that is core to the job, or a humble-brag.",
    keywords: ["weakness", "improve", "example", "result"],
    difficulty: 1,
    roles: ["BACKEND", "FRONTEND", "FULLSTACK", "DEVOPS", "SDE"],
  },
  {
    category: "HR",
    question: "Why should we hire you?",
    short: "I can already build and explain production-style features end to end — auth, databases, tests and deployment — and I learn fast. In my notes API I found and fixed an IDOR bug through tests, which is the kind of ownership I'd bring here.",
    deep: "Match **their needs** (from the JD) to **your evidence**. One concrete story beats five adjectives.",
    followUps: ["What would you do in your first 30 days?"],
    commonMistake: "Generic adjectives ('hardworking, passionate') with no proof.",
    keywords: ["project", "skills", "team|company", "example"],
    difficulty: 1,
    roles: ["BACKEND", "FRONTEND", "FULLSTACK", "DEVOPS", "SDE"],
  },
  {
    category: "PROJECTS",
    question: "Walk me through a project you built and one bug you fixed.",
    short: "I built a notes REST API with Express and PostgreSQL. While testing, I found that changing the note id in the URL returned another user's note — an IDOR bug. I fixed it by scoping every query by the logged-in user's id and added a test for it.",
    deep: "Use **STAR**: Situation (what and why), Task (your part), Action (decisions, the bug, how you debugged), Result (numbers, what you learned). Be ready to draw the architecture.",
    followUps: ["How would you scale it?", "What would you do differently?", "How did you test it?"],
    commonMistake: "Describing features instead of decisions, or being unable to explain code you shipped.",
    keywords: ["built", "bug", "fixed", "test", "decision|because"],
    difficulty: 2,
    roles: ["BACKEND", "FRONTEND", "FULLSTACK", "SDE"],
  },
  {
    category: "SYSTEM_DESIGN",
    question: "Design a URL shortener.",
    short: "Clarify scale (e.g. 100M URLs, read-heavy). Generate short codes with base62 on a unique id, store code→URL in a key-value table, put a cache in front for hot links, and redirect with 301/302. Add rate limiting and analytics via an async queue.",
    deep: "1. **Requirements**: create, redirect, optional expiry, analytics.\n2. **Estimates**: reads ≫ writes.\n3. **API**: `POST /urls`, `GET /:code`.\n4. **Data**: code (PK), url, createdAt, expiresAt.\n5. **Code generation**: base62 of an id from a sequence or Snowflake; avoid hash collisions.\n6. **Scale**: cache, read replicas, CDN edge redirects.\n7. **Trade-offs**: 301 is cacheable (less analytics), 302 keeps analytics.",
    followUps: ["How do you avoid collisions?", "How would you count clicks without slowing redirects?"],
    commonMistake: "Jumping to microservices before clarifying requirements and scale.",
    keywords: ["base62|hash", "cache", "redirect", "database", "scale"],
    difficulty: 2,
    roles: ["BACKEND", "FULLSTACK", "SDE"],
  },
  {
    category: "SYSTEM_DESIGN",
    question: "How would you design a notification system?",
    short: "Producers publish events to a queue; a notification service applies user preferences and templates, then fans out to channel workers (email, SMS, push) with retries, rate limits and idempotency keys so users don't get duplicates.",
    deep: "Cover **preferences**, **templates**, **priority queues**, **retries with backoff**, **dead-letter queues**, **idempotency**, and **delivery tracking**.",
    followUps: ["How do you prevent duplicate notifications?", "How do you handle a provider outage?"],
    commonMistake: "Sending notifications synchronously inside the user's request.",
    keywords: ["queue", "retry", "idempoten", "worker", "preference"],
    difficulty: 3,
    roles: ["BACKEND", "FULLSTACK", "SDE"],
  },
];
