/**
 * The complete Prompters curriculum skeleton (PRD stages 0–8).
 * Topics listed here without a content file are seeded as COMING_SOON so the
 * roadmap never silently drops a topic.
 */

export type StageTrack = "COMMON" | "PYTHON" | "JAVASCRIPT";

export interface SeedStage {
  slug: string;
  code: string;
  title: string;
  description: string;
  track: StageTrack;
  order: number;
  estHours: number;
  targetRoles: string[];
  modules: { slug: string; title: string; description: string; topics: [slug: string, title: string][] }[];
}

const ALL_ROLES = ["BACKEND", "FRONTEND", "FULLSTACK", "DEVOPS"];

export const curriculum: SeedStage[] = [
  {
    slug: "foundations",
    code: "0",
    title: "Foundations",
    description: "How computers, programs and the web actually work — from zero.",
    track: "COMMON",
    order: 0,
    estHours: 12,
    targetRoles: ALL_ROLES,
    modules: [
      {
        slug: "how-computers-work",
        title: "How computers work",
        description: "Binary, hardware and how a program runs.",
        topics: [
          ["binary-bits-bytes", "Binary, bits and bytes"],
          ["cpu-ram-storage", "CPU, RAM and storage"],
          ["operating-system-basics", "Operating system, processes and programs"],
          ["how-code-runs", "How code runs: compiler vs interpreter"],
        ],
      },
      {
        slug: "developer-tools",
        title: "Developer tools",
        description: "Terminal, files, environment and Git.",
        topics: [
          ["terminal-basics", "Terminal and CLI basics"],
          ["files-and-paths", "Files, directories and paths"],
          ["environment-variables-path", "Environment variables and PATH"],
          ["package-managers", "Package managers"],
          ["vscode-setup", "Setting up VS Code"],
          ["git-basics", "Git basics"],
          ["github-basics", "GitHub and remote repositories"],
        ],
      },
      {
        slug: "how-the-web-works",
        title: "How the web works",
        description: "Internet, DNS, HTTP and JSON.",
        topics: [
          ["internet-client-server", "Internet and the client–server model"],
          ["ip-ports-dns", "IP addresses, ports and DNS"],
          ["http-request-response", "HTTP request and response"],
          ["https-basics", "HTTPS basics"],
          ["how-browsers-work", "How a browser loads a page"],
          ["json-basics", "JSON"],
          ["what-is-an-api", "What is an API?"],
        ],
      },
    ],
  },
  {
    slug: "python",
    code: "1A",
    title: "Start with Python",
    description: "Python from first line to OOP, testing and APIs.",
    track: "PYTHON",
    order: 1,
    estHours: 40,
    targetRoles: ALL_ROLES,
    modules: [
      {
        slug: "python-fundamentals",
        title: "Python fundamentals",
        description: "Variables to modules.",
        topics: [
          ["py-variables-types", "Variables and data types"],
          ["py-input-output", "Input and output"],
          ["py-operators", "Operators"],
          ["py-conditions", "Conditions (if / elif / else)"],
          ["py-loops", "Loops"],
          ["py-functions", "Functions, parameters and return values"],
          ["py-lists-tuples", "Lists and tuples"],
          ["py-sets-dicts", "Sets and dictionaries"],
          ["py-strings-slicing", "Strings and slicing"],
          ["py-files", "Working with files"],
          ["py-exceptions", "Exceptions"],
          ["py-modules-packages", "Modules and packages"],
          ["py-pip-venv", "pip and virtual environments"],
        ],
      },
      {
        slug: "python-intermediate",
        title: "Python intermediate",
        description: "OOP, comprehensions, generators, testing.",
        topics: [
          ["py-oop-classes", "Classes and objects"],
          ["py-oop-pillars", "Inheritance, composition, encapsulation, polymorphism"],
          ["py-comprehensions", "Comprehensions"],
          ["py-iterators-generators", "Iterators and generators"],
          ["py-decorators", "Decorators"],
          ["py-context-managers", "Context managers"],
          ["py-args-kwargs", "*args and **kwargs"],
          ["py-type-hints-dataclasses", "Type hints and dataclasses"],
          ["py-pytest", "Testing with pytest"],
          ["py-requests-json-csv", "requests, JSON and CSV"],
        ],
      },
    ],
  },
  {
    slug: "javascript",
    code: "1B",
    title: "Start with JavaScript",
    description: "JavaScript basics through closures, async and the DOM.",
    track: "JAVASCRIPT",
    order: 1,
    estHours: 40,
    targetRoles: ALL_ROLES,
    modules: [
      {
        slug: "js-fundamentals",
        title: "JavaScript fundamentals",
        description: "Variables to modules.",
        topics: [
          ["js-variables-types", "Variables (let, const, var) and types"],
          ["js-operators-conditions", "Operators and conditions"],
          ["js-loops", "Loops"],
          ["js-functions", "Functions"],
          ["js-arrays", "Arrays and array methods"],
          ["js-objects", "Objects"],
          ["js-strings", "Strings"],
          ["js-destructuring-spread", "Destructuring, spread and rest"],
          ["js-dom-events", "DOM and events"],
          ["js-modules-npm", "Modules, npm and package.json"],
        ],
      },
      {
        slug: "js-intermediate",
        title: "JavaScript intermediate",
        description: "Scope, closures, prototypes, async.",
        topics: [
          ["js-scope-hoisting", "Scope and hoisting"],
          ["js-closures", "Closures"],
          ["js-this", "The this keyword"],
          ["js-prototypes-classes", "Prototypes and classes"],
          ["js-promises", "Promises"],
          ["js-async-await", "Async / await"],
          ["js-event-loop", "The event loop, microtasks and macrotasks"],
          ["js-fetch", "fetch and working with APIs"],
          ["js-error-handling", "Error handling"],
        ],
      },
    ],
  },
  {
    slug: "programming-core",
    code: "2",
    title: "Programming core",
    description: "DSA patterns and CS fundamentals every interview tests.",
    track: "COMMON",
    order: 2,
    estHours: 80,
    targetRoles: ALL_ROLES,
    modules: [
      {
        slug: "dsa",
        title: "Data structures and algorithms",
        description: "Big-O to dynamic programming, pattern by pattern.",
        topics: [
          ["big-o", "Big-O notation"],
          ["arrays-strings", "Arrays and strings"],
          ["hashing", "Hashing and hash maps"],
          ["two-pointers", "Two pointers"],
          ["sliding-window", "Sliding window"],
          ["prefix-sum", "Prefix sum"],
          ["binary-search", "Binary search"],
          ["sorting", "Sorting"],
          ["recursion", "Recursion"],
          ["stacks-queues", "Stacks, queues and deques"],
          ["linked-lists", "Linked lists"],
          ["trees-bst", "Trees and BST"],
          ["heaps", "Heaps and priority queues"],
          ["graphs-bfs-dfs", "Graphs, BFS and DFS"],
          ["backtracking", "Backtracking"],
          ["dynamic-programming", "Dynamic programming"],
          ["greedy", "Greedy algorithms"],
          ["tries", "Tries"],
          ["intervals", "Intervals"],
          ["bit-manipulation", "Bit manipulation"],
        ],
      },
      {
        slug: "cs-fundamentals",
        title: "CS fundamentals",
        description: "OOP/SOLID, OS, networks and DBMS.",
        topics: [
          ["oop-solid", "OOP and SOLID"],
          ["os-processes-threads", "Processes and threads"],
          ["os-concurrency-deadlocks", "Concurrency and deadlocks"],
          ["os-memory-scheduling", "Memory management and scheduling"],
          ["net-tcp-udp", "TCP vs UDP"],
          ["net-tls", "TLS and HTTPS in depth"],
          ["net-websockets", "WebSockets"],
          ["dbms-normalization", "Normalization"],
          ["dbms-acid-transactions", "ACID and transactions"],
          ["dbms-keys-constraints", "Keys and constraints"],
        ],
      },
    ],
  },
  {
    slug: "frontend",
    code: "3",
    title: "Frontend",
    description: "HTML, CSS, Tailwind, TypeScript, React and Next.js.",
    track: "COMMON",
    order: 3,
    estHours: 70,
    targetRoles: ["FRONTEND", "FULLSTACK"],
    modules: [
      {
        slug: "web-basics",
        title: "Web basics",
        description: "Semantic HTML, CSS layout and Tailwind.",
        topics: [
          ["html-semantic", "Semantic HTML"],
          ["html-forms", "HTML forms"],
          ["html-accessibility-seo", "Accessibility and SEO"],
          ["css-box-model", "The box model"],
          ["css-flexbox", "Flexbox"],
          ["css-grid", "CSS Grid"],
          ["css-responsive", "Responsive design and media queries"],
          ["css-animations", "Transitions and animations"],
          ["css-specificity-variables", "Specificity and CSS variables"],
          ["tailwind", "Tailwind CSS"],
          ["browser-storage-cookies", "Storage and cookies"],
          ["cors", "CORS"],
        ],
      },
      {
        slug: "react-next",
        title: "React, TypeScript and Next.js",
        description: "Components to server rendering.",
        topics: [
          ["ts-basics", "TypeScript types and interfaces"],
          ["ts-generics-narrowing", "Generics, unions and narrowing"],
          ["react-components-props", "Components and props"],
          ["react-state", "State and useState"],
          ["react-effects", "useEffect"],
          ["react-hooks-advanced", "useMemo, useCallback, useRef"],
          ["react-context", "Context and state management"],
          ["react-forms", "Forms and validation"],
          ["react-routing", "Routing"],
          ["react-data-fetching", "Data fetching"],
          ["react-performance", "Performance and lazy loading"],
          ["next-app-router", "Next.js App Router"],
          ["next-server-components", "Server and client components"],
          ["next-rendering", "SSR, SSG and ISR"],
          ["next-caching-deploy", "Caching and deployment"],
        ],
      },
    ],
  },
  {
    slug: "backend",
    code: "4",
    title: "Backend",
    description: "APIs, databases, caching, queues and security.",
    track: "COMMON",
    order: 4,
    estHours: 90,
    targetRoles: ["BACKEND", "FULLSTACK"],
    modules: [
      {
        slug: "server-development",
        title: "Server development",
        description: "HTTP, Node.js, Express and API design.",
        topics: [
          ["http-methods-status", "HTTP methods and status codes"],
          ["http-headers-cookies", "Headers, cookies and sessions"],
          ["rest-api-design", "REST API design"],
          ["node-runtime", "Node.js runtime"],
          ["express-routing", "Express routing"],
          ["express-middleware", "Middleware"],
          ["input-validation", "Input validation"],
          ["error-handling-backend", "Error handling"],
          ["pagination-filtering", "Pagination, filtering and sorting"],
          ["file-uploads", "File uploads"],
          ["websockets-realtime", "WebSockets and real-time"],
          ["background-jobs-queues", "Background jobs and queues"],
          ["layered-architecture", "Layered architecture and modular monolith"],
          ["backend-testing", "Testing APIs"],
          ["fastapi-basics", "FastAPI fundamentals"],
        ],
      },
      {
        slug: "databases",
        title: "Databases",
        description: "SQL, PostgreSQL, indexing, ORMs, MongoDB and Redis.",
        topics: [
          ["sql-basics", "SQL basics"],
          ["sql-joins", "SQL joins"],
          ["schema-design", "Schema design"],
          ["db-indexes", "Indexes"],
          ["db-transactions-locks", "Transactions and locks"],
          ["query-optimization", "Query optimisation and EXPLAIN"],
          ["orms-prisma", "ORMs (Prisma, SQLAlchemy)"],
          ["mongodb-basics", "MongoDB basics"],
          ["redis-caching", "Redis and caching"],
        ],
      },
      {
        slug: "security",
        title: "Security",
        description: "Auth, authorisation and the OWASP Top 10.",
        topics: [
          ["password-hashing", "Password hashing"],
          ["sessions-vs-jwt", "Sessions vs JWT"],
          ["jwt-authentication", "JWT authentication"],
          ["oauth-basics", "OAuth basics"],
          ["rbac", "Role-based access control"],
          ["multi-tenancy", "Multi-tenancy"],
          ["idor", "IDOR"],
          ["injection-xss-csrf", "Injection, XSS and CSRF"],
          ["rate-limiting", "Rate limiting"],
          ["owasp-top-10", "OWASP Top 10"],
        ],
      },
    ],
  },
  {
    slug: "devops",
    code: "5",
    title: "DevOps",
    description: "Linux, Docker, CI/CD, cloud and monitoring.",
    track: "COMMON",
    order: 5,
    estHours: 60,
    targetRoles: ["DEVOPS", "BACKEND", "FULLSTACK"],
    modules: [
      {
        slug: "operations-delivery",
        title: "Operations and delivery",
        description: "From a Linux shell to production deploys.",
        topics: [
          ["linux-basics", "Linux basics"],
          ["linux-permissions-processes", "Permissions and processes"],
          ["shell-scripting", "Shell scripting"],
          ["ssh", "SSH"],
          ["git-workflows", "Git workflows and pull requests"],
          ["docker-basics", "Docker images and containers"],
          ["dockerfile", "Writing a Dockerfile"],
          ["docker-compose", "Docker Compose"],
          ["nginx-reverse-proxy", "Nginx and reverse proxies"],
          ["ci-cd-github-actions", "CI/CD with GitHub Actions"],
          ["aws-core", "AWS EC2, S3, IAM and RDS"],
          ["monitoring-logging", "Monitoring, logging and health checks"],
          ["deployment-strategies", "Deployment strategies and rollback"],
          ["kubernetes-basics", "Kubernetes basics"],
          ["terraform-basics", "Terraform basics"],
        ],
      },
    ],
  },
  {
    slug: "system-design",
    code: "6",
    title: "System design",
    description: "Designing at scale, from zero to case studies.",
    track: "COMMON",
    order: 6,
    estHours: 50,
    targetRoles: ["BACKEND", "FULLSTACK", "DEVOPS"],
    modules: [
      {
        slug: "design-at-scale",
        title: "Designing at scale",
        description: "Building blocks of large systems.",
        topics: [
          ["what-is-scalability", "What does scalable mean?"],
          ["load-balancing", "Load balancing"],
          ["caching-at-scale", "Caching and CDNs"],
          ["replication", "Replication and read replicas"],
          ["sharding", "Sharding"],
          ["queues-pubsub", "Queues and pub/sub"],
          ["cap-consistency", "Consistency and CAP"],
          ["api-design-at-scale", "API design and rate limiting at scale"],
          ["microservices", "Microservices and service discovery"],
          ["fault-tolerance-observability", "Fault tolerance and observability"],
        ],
      },
      {
        slug: "case-studies",
        title: "Case studies",
        description: "Requirements → estimates → design → trade-offs.",
        topics: [
          ["cs-url-shortener", "Design a URL shortener"],
          ["cs-chat-app", "Design a chat app"],
          ["cs-news-feed", "Design a news feed"],
          ["cs-job-portal", "Design a job portal"],
          ["cs-payments", "Design a payment system"],
          ["cs-notifications", "Design a notification system"],
          ["cs-file-storage", "Design file storage"],
          ["cs-video-platform", "Design a video platform"],
          ["cs-food-delivery", "Design food delivery"],
        ],
      },
    ],
  },
  {
    slug: "applied-ai",
    code: "7",
    title: "Applied AI",
    description: "Using LLMs professionally: APIs, embeddings, RAG and safety.",
    track: "COMMON",
    order: 7,
    estHours: 30,
    targetRoles: ["BACKEND", "FULLSTACK"],
    modules: [
      {
        slug: "ai-for-developers",
        title: "AI for developers",
        description: "How LLMs work and how to build with them.",
        topics: [
          ["llm-basics", "How LLMs work: tokens and context"],
          ["prompt-engineering", "Prompt engineering"],
          ["llm-apis-structured-output", "LLM APIs, structured output and tool use"],
          ["embeddings", "Embeddings and similarity search"],
          ["vector-databases", "Vector databases"],
          ["rag", "RAG: chunking, retrieval and reranking"],
          ["ai-evaluation", "Evaluation and hallucination"],
          ["ai-security", "AI security and prompt injection"],
          ["ai-cost-control", "Cost control and caching"],
          ["ai-agents", "Agents and AI application architecture"],
        ],
      },
    ],
  },
  {
    slug: "job-readiness",
    code: "8",
    title: "Job readiness",
    description: "Interviews, resume, profiles and applications.",
    track: "COMMON",
    order: 8,
    estHours: 25,
    targetRoles: ALL_ROLES,
    modules: [
      {
        slug: "interview-career",
        title: "Interview and career",
        description: "Turn skills into offers.",
        topics: [
          ["project-storytelling", "Project storytelling (STAR)"],
          ["resume-writing", "Writing an ATS-friendly resume"],
          ["linkedin-naukri", "LinkedIn and Naukri profiles"],
          ["hr-questions", "HR and behavioural questions"],
          ["application-strategy", "Application strategy"],
          ["offer-negotiation", "Offer negotiation basics"],
        ],
      },
    ],
  },
];
